version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3210:3210"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: >
      sh -c "pnpm dev"
    restart: unless-stopped
